openapi: 3.0.0
info:
  title: History API
  version: 1.0.0
paths:
  /question/{qid}:
    get:
      tags:
        - 试题
      summary: 根据试题id查询试题
      parameters:
        - name: qid
          in: path
          description: 试题id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 查询到的试题
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Question'

  /question/{qid}/knowledge:
    get:
      tags:
        - 试题
      summary: 根据试题id查询试题的知识点
      parameters:
        - name: qid
          in: path
          description: 试题id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 查询到的知识点列表
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /question/list:
    get:
      tags:
        - 试题
      summary: 查询试题列表
      parameters:
        - name: pageNum
          in: query
          description: 分页页码, 当前页码
          required: false
          schema:
            type: integer
            default: 1
        - name: pageSize
          in: query
          description: 分页页码, 当前页码
          required: false
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: 试题列表
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Question'

  /knowledge/questions:
    get:
      tags:
        - 知识点
      summary: 根据知识点查询试题
      parameters:
        - name: k
          in: query
          description: k 知识点名称
          required: false
          schema:
            type: string
      responses:
        '200':
          description: 试题列表
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Question'

  /knowledge/list:
    get:
      tags:
        - 知识点
      summary: 查询知识点列表
      parameters:
        - name: pageNum
          in: query
          description: 分页页码, 当前页码
          required: false
          schema:
            type: integer
            default: 1
        - name: pageSize
          in: query
          description: 分页页码, 当前页码
          required: false
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: 知识点列表
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Knowledge'

components:
  schemas:
    Option:
      type: object
      properties:
        key:
          type: string
          description: 选项
        value:
          type: string
          description: 选项取值
    Question:
      type: object
      properties:
        id:
          type: string
          description: 试题id
        question:
          type: string
          description: 试题题干
        type:
          type: string
          description: 试题类型
        complexity:
          type: number
          description: 试题复杂度，浮点型
        option:
          type: array
          description: 试题选项
          items:
            $ref: '#/components/schemas/Option'
        knowledge:
          type: string
          description: 试题所属知识点
        answer:
          type: string
          description: 答案
        analysis:
          type: string
          description: 试题分析
        created_at:
          type: string
          description: 试题创建时间,字符串格式
        updated_at:
          type: string
          description: 试题更新时间,字符串格式
    Knowledge:
      type: object
      properties:
        name:
          type: string
          description: 知识点名称
        created_at:
          type: string
          description: 试题创建时间,字符串格式
        updated_at:
          type: string
          description: 试题更新时间,字符串格式
